### ISSUE TITLE
By Component Removed | What's The New Best Way To Only Add Acceleration To My Y Axis While Keeping My X Axis 1:1?

### ISSUE THREAD

**Issue by KingOwnageXV** [a1xd/rawaccel#100]
Here is a link to my original issue from a long time ago: https://github.com/a1xd/rawaccel/issues/61

I've noticed that by component was removed from the application, so I now need to know what's the best way to only add acceleration to my Y axis while keeping my X axis 1:1?

A developer replied stating they would add something better without the curl that by component adds, idk if its been added yet but what's the new best way to accomplish what I'm trying to do?

**Comment by GitLinker** [comment]
Anisotropy drop down still has component, and domain and range to change your y-axis while keeping your x-axis. 
It's in the [documentation](https://github.com/a1xd/rawaccel/blob/master/doc/Guide.md) under **"Horizontal and Vertical"**.
