### ISSUE TITLE
Raw Accel breaks mouse after pc wakes up from sleep.

### ISSUE THREAD

**Issue by razenxd** [a1xd/rawaccel#101]
Hi,
I'm experiencing this issue in both of my PC's.
The one is a Ryzen 2600 Based system and the other one is a Q6600 based system.
Both computers on w10 with latest updates. And I use WMO 1.1a on both.
Seems that 8/10 times that I wake up the pc from sleep mode the mouse is broken.
It becoming less slow than the pre raw accel situation and also skips a lot.
Disabling/re enabling the Raw Accel made no difference but a reboot makes it work like a charm again.
To be clear, the situation occuring ONLY when raw accel is enabled before pc going to sleep.
Never experienced that issue when Raw accel isn't enabled.
Any ideas?
Thanks

**Comment by a1xd** [comment]
v1.5 is optimized which may help

if this issue only occurs when accel is enabled, try setting the polling rate field in the new Advanced >> device menu, might help polling/timing related stutters
