### ISSUE TITLE
Motivity is unnecesserily complicated, this GUI change should make it better

### ISSUE THREAD

**Issue by GrayFace** [a1xd/rawaccel#103]
ATM Gain goes from `Sens/Motivity` to `Sens*Motivity`. While keeping the same params internally, it could be displayed in the GUI the same way as other modes by making it go from `Sens` to `Sens*Limit`. This way it would be easy to switch to and easier to tweak. Params can still be saved the same way as before for compatibility: `Motivity = Limit^0.5`, `Sens_Saved = Sens_GUI*Motivity`.

**Comment by JacobPalecki** [comment]
Generally we agree with the sentiment, but don't want to present motivity like this for other reasons.
