### ISSUE TITLE
sensitivity breaks in minecraft versions with lwjgl 3

### ISSUE THREAD

**Issue by verified-gamer** [a1xd/rawaccel#104]
when using the raw accel driver, minecraft java versions after 17w43a have a extreme high sensitivity instead of the sensitivity without the raw accel driver. minecraft java versions of 1.12.2 or lower have not chanced their sensitivity, this may have something to do with lwjgl 3

my sens multiplier: 20
minecraft 17w43 patch notes: www.minecraft.net/nl-nl/article/minecraft-snapshot-17w43a

**Comment by JacobPalecki** [comment]
Raw Accel knows absolutely nothing about what game you are playing, or whether you are playing a game. Raw Accel only sends your mouse counts through a math formula to generate an edited set of mouse counts to send to Windows, who then sends it to whatever program (such as MineCraft.) Whatever issue you are having is between you and MineCraft; it is not possible that RA is involved.

**Comment by verified-gamer** [comment]
uninstalling the raw accel driver does fix the issue thoug

**Comment by JacobPalecki** [comment]
It is possible that you had RawAccel misconfigured - too high of a sensitivity multiplier, or an acceleration curve which increased your sensitivity too high for your typical hand motions. Thus, uninstalling RawAccel fixed your issue. lwjgl 3 would have to be doing something really gross\incorrect to cause a problem with RawAccel, which is always possible, but I'd doubt. When I have some time I may check.

**Comment by verified-gamer** [comment]
did some more testing, it seems like minecraft versions that have lwjgl 3 ignore the windows mouse speed setting, but do see the multiplied speed from raw accel

**Comment by verified-gamer** [comment]
that might still be considered a bug, although my first idea was wrong

**Comment by JacobPalecki** [comment]
Not a bug. That means lwgjl 3 gets its mouse counts from the Raw Input queue rather than from windows mouse, which means that windows mouse settings are ignored. But many games use the Raw Input queue. Raw Accel is called "Raw" Accel specifically because it accelerates mouse counts in the Raw Input queue, so it is working exactly as intended.

**Comment by verified-gamer** [comment]
oke, thanks for the explanation
