### ISSUE TITLE
Invalid chart range

### ISSUE THREAD

**Issue by Radi00** [a1xd/rawaccel#112]
Idk how to fix, it was all normal until i started program again and msg showed up ''Invalid chart range''

**Comment by Radi00** [comment]
> I'm having the same issue, restarting the pc and reinstalling the driver didn't fix it.

I'm gonna try something and let you know how to fix.... If i fix.

**Comment by Kalistence** [comment]
Ah ok thanks :)

**Comment by a1xd** [comment]
patched on latest release
