### ISSUE TITLE
Is there a reason for 1.6 dropping support for Win 7?

### ISSUE THREAD

**Issue by GrayFace** [a1xd/rawaccel#115]
If you need somebody to test on Win 7, I'd do it.

**Comment by torriz** [comment]
Maybe because Win 7 is EOL?

**Comment by GrayFace** [comment]
That's not a valid reason on its own. If Win 7 support is a hassle, then that's a reason, which is why I'm asking.

**Comment by JacobPalecki** [comment]
Microsoft discontinued the signing of new kernel drivers for Windows 7 in April.
