### ISSUE TITLE
is there a way to make cinematic mouse with this?

### ISSUE THREAD

**Issue by Sandr0002** [a1xd/rawaccel#117]
hello, is there a way to set settings like in Minecraft cinematic mode? I want to move my mouse like that in other games for cinematic shots

**Comment by a1xd** [comment]
so cinematic mode limits your turn rate? there's a similar option you can use

open `settings.json` in a text editor and look for `"Input Speed Cap"`
change that value to the cap you want (in counts/ms), then run `rawaccel.exe` for it to take effect
