### ISSUE TITLE
Choosing classic options leads me back to linear

### ISSUE THREAD

**Issue by migswn** [a1xd/rawaccel#118]
Thank you for the program! However a problem I noticed was that whenever I’d change from Linear to Classic, when Apply it changes back to linear, even after reset and choosing classic right away

**Comment by Fuwn** [comment]
This behaviour is because linear is just classic with an power (exponent) of 2 ([source](https://github.com/a1xd/rawaccel/blob/master/doc/Guide.md#classic)).

If the power input field within classic is set to 2, the default, upon application your acceleration method will be set to linear.
