### ISSUE TITLE
[Enhancement Request] - Jitter / Shaky. Option for mouse movement smoothing.

### ISSUE THREAD

**Issue by Qceil** [a1xd/rawaccel#119]
###  Enhancement request.

Specific speed range mouse slide  _smoothing / stabilization_ filter.

**My equipment.**
   Mouse 12000 dpi .

**Issues obstructing smooth mouse slide flow.**
   Slight jerking due to micro gripping of mouse pad or muscle stutter / tremor / twitching / jitter / noise.

   Afflicting the smooth tracking / pacing of targets in motion.

   
**Concept examples.**
- [Accessibility program for Parkinson's afflicted. _Stabilizing_ method.](https://www.steadymouse.com/) This program would be   close to what I'm requesting however it does not work in game. It also works for the entirety of mouse movement, on all the time instead of during specific speed range. Not really needed in high-speed movement.

-    [Camcorder image _smoothing / stabilizing_ .](https://www.youtube.com/watch?v=P2-WM2SPh8g) A very good example of the _stabilizing_ concept.

-    [ _Stabilization_ method while target shooting down range.](https://www.youtube.com/watch?v=f75lLgRoZus) Breakdown and expounding of concept.

-    [Project program adds the function of _smoothing_ to your mouse.](https://www.codeproject.com/Articles/5247322/Mouse-Smoothing) With code examples.

**Requesting filter for smoothing motion in specified speed range to aid in...** 
-  Jittery / shaky / twitchy / tremor / noise / adrenaline muscle spasm / stuttering

**For the purpose of pacing targets in motion.**
-  _Stabilizing / smoothing / normalizing / dampening / clean tracking motion control_.

   

 Thank for your time and consideration.

**Comment by JacobPalecki** [comment]
Smoothing is not something either author has a desire to add for their own use and not something any other users have been asking for. In general, smoothing considers micro-movements as something to be cleaned\changed, whereas in competitive games those micro-movements are essential for aiming. Most smoothing formulas add some latency as well as future inputs are required to process the current one. It's my opinion that it would bloat the program but if someone added it to Raw Accel with a nicely-done implementation I'd consider it; I won't be adding it myself.
