### ISSUE TITLE
Advanced settings

### ISSUE THREAD

**Issue by iLIKE2STAYU** [a1xd/rawaccel#122]
Why do I only have 2 advanced settings & not the rest ? Do I have to unlock them or something ? For some reason I don’t have capstyle & the other advanced settings. I can only disable peripherals.

**Comment by JacobPalecki** [comment]
The other advanced menu options have been moved to other parts of the UI. Check out 1.6.0 release notes. Cap style, for instance, is now displayed next to the settings for a specific accel type.

**Comment by iLIKE2STAYU** [comment]
So none of the versions have the extra settings ? i kind of want the extra settings. Idc if I have to download an old version

**Comment by JacobPalecki** [comment]
No, they're _moved to other parts of the GUI_. Which one in particular are you looking for?

**Comment by iLIKE2STAYU** [comment]
Well if you are referring to any version above 1.4.1 then the enable feature, capstyle & offset style have been removed from the interface. 

1.4.1 has the enable feature aswell as the extra advanced settings I was looking for.
