### ISSUE TITLE
"Re-scale by above" broken in Windows 11

### ISSUE THREAD

**Issue by ExperimentalDJ** [a1xd/rawaccel#123]
In the GUI under Charts -> Scale by Mouse Settings -> "Re-scale by above" does not do anything.

These settings both properly update and save the input.
 Charts -> Scale by Mouse Settings -> DPI
 Charts -> Scale by Mouse Settings -> Poll Rate

The "Re-scale by above" does not change anything based on these settings. Changing DPI & Poll Rate from 1 to 100,000 results in no difference when clicking "Re-scale by above".

The DPI & Poll Rate options under Advanced -> Device Menu, work properly. Changing those values will instantly update the acceleration settings.
(Ticking "Override Defaults" on/off changes nothing about this issue)

This was happening on a fresh install of Windows 11. I have since installed quite a few programs, and the issue remains.

**Comment by a1xd** [comment]
try pressing the enter key inside those fields if you haven't already

for some reason, it's required for the "Re-scale" to apply

**Comment by a1xd** [comment]
enter key press isn't required as of v1.6.1
