### ISSUE TITLE
Convex function?

### ISSUE THREAD

**Issue by Malidictus** [a1xd/rawaccel#125]
It seems like most of the functions available for mouse sensitivity are all concave - quick ramp-up, then gradual diminishing returns. Wouldn't it make sense to have a convex function, as well - something with a gradual ramp-up, then a rapid increase? A basic exponential function (say, quadratic) would produce something like that. Or would that be unwieldy to use?

I'm trying to achieve a decent dead zone of low-ish sensitivity for fine movement, along a decently large increase in sensitivity for spinning around in video games or covering the entire desktop with a flick. The concave functions on offer seem to give me one or the other, but not both.

**Comment by a1xd** [comment]
classic mode with power > 2 is convex, imo it's unwieldy without a cap

> dead zone of low-ish sensitivity for fine movement, along a decently large increase in sensitivity

try out linear mode with an offset if you haven't yet

**Comment by Malidictus** [comment]
Thank you, I'll definitely try that out. I spent quite a while experimenting. Eventually, I settled on Motivity with a bias towards 0. That gives me a convex segment at the start with a concave segment past the inflection point, which is pretty much what I was hoping for. Takes a bit of getting used to since my mouse very tangibly speeds up if I move it "a bit more quickly," but it works far better for what I need than any of the pure concave functions. I don't think this was in the older versions, either.

In either case, thank you so much for making this :) It's an absolute godsend and I genuinely wish more people would adopt it. Or at the very least roll back on the mouse acceleration hate a little.

**Comment by ThomasGrowley** [comment]
For trackballs acceleration is very helpful. Similar to what you were asking about , yes I use motivity for the same reason - precision at slow speed and ability to move quickly. In case it gives you ideas, here are my settings for the ploopy thumb. DPIs are 6000,12000, so Sens multiplier 0.1 to get effectively 600/1200 DPI. Growth rate 1.5. Motivity 2. Midpoint 30.

**Comment by Malidictus** [comment]
I'm using a regular mouse. Switched to a Razer Naga for the thumb buttons when the old one died. I actually use similar settings. 1600 DPI at 0.5 multiplier and 1.5 and 2 for growth and motivity. Set the midpoint to 5, though - so quite a bit lower. Seems to "squash" the graph to the left. I'm apparently slow with my hand, so that helps.

I can't find a way to save profiles, so I'm worried about messing with my settings from where they seem to work for now.
