### ISSUE TITLE
Doesn't work in certain games

### ISSUE THREAD

**Issue by phorgen** [a1xd/rawaccel#126]
Doesn't work in Doom, osu if i activate raw input and Ultralkill but i does work in Apex, Desktop, and osu if raw input is deactivated. (I also have a drawing tablet that isn't affected but that assigns  positions on the table to  positions on the screen)

**Comment by a1xd** [comment]
if it works in one game it works invariably; in all programs

set your sens multiplier to something comically low, like 0.001, and you'll see that is the case

the difference you feel is probably due to the "Enhance Pointer Precision" mouse setting (Windows accel)
