### ISSUE TITLE
Windows 7 and 8.1 Support

### ISSUE THREAD

**Issue by muratcansimsek** [a1xd/rawaccel#131]
Low end spec gamers still playing on Windows 7 and 8.1.

Is there way to improve this software?

**Comment by rbenzazon** [comment]
I would be interested too

**Comment by torriz** [comment]
Use a older version of rawaccel that is supported by Windows 7.

Win 7 reached it's EOL (end of life) January 14, 2020, and receives no more security updates from Microsoft, so it makes no sense for rawaccel to continue to support it either. You really shouldn't continue to use Windows 7 at this point, as it puts you at risk.

**Comment by a1xd** [comment]
you're stuck with v1.5
