### ISSUE TITLE
Linux Version pls

### ISSUE THREAD

**Issue by CyberGh0st-droid** [a1xd/rawaccel#140]
I would love to see a linux version of this tool it would be so awesome. I know there are other linux alternatives like Leetmouse and mouse driver, but none of them shows the graph and I couldn't get the Leetmouse-GUI to work. and since I'm so new to linux it's very confusing for me to go and edit the values in the files.

**Comment by JacobPalecki** [comment]
https://github.com/a1xd/rawaccel/issues/96
