### ISSUE TITLE
,,Raw accel is not installed" even though I installed it. 

### ISSUE THREAD

**Issue by TopfSicko** [a1xd/rawaccel#147]
Hello, 
I wanted to download raw accel and I watched and followed several tutorials.
First I downloaded all the necessary files etc.
I ran the installer.exe, then restarted my pc and then tried to open RawAccel but it says I haven't downloaded raw accel.
 

I also had this error file in the folder:
InteropException: Raw Accel is not installed, run installer.exe
   at VersionHelper.ValidOrThrow()
   at grapher.RawAcceleration..ctor()
   at grapher.Program.Main()

![Screenshot 2022-08-16 181551](https://user-images.githubusercontent.com/94565768/184928551-61ec0d38-cb08-4e15-9cdf-41370ad240fd.png) <--- error

**Comment by a1xd** [comment]
try restarting from Start Menu -> Power -> Restart, other methods like Shutdown or using the power button aren't guaranteed to work

if that doesn't do it, then there must be an antivirus/security issue. you could try turning off tamper protection and controlled folder access in the Windows Security virus & threat protection settings, then run the installer again
