### ISSUE TITLE
Can't run Raw Accel

### ISSUE THREAD

**Issue by Zesify** [a1xd/rawaccel#155]
Whenever I try to run raw accel it shows an error saying:-
Could not Load Type 'System.ValueTuple`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a561934e089'.
I don't know why, even i have tried some of the older verion of raw accel but still its shows the same error please help it will means a lot to me. 
![IMG_20220916_170350](https://user-images.githubusercontent.com/113691415/190635216-db8fc70b-4b43-4661-b3ef-2cfd0280d0a2.jpg)

**Comment by a1xd** [comment]
update .NET - https://github.com/a1xd/rawaccel/blob/master/doc/Guide.md#installation
