### ISSUE TITLE
rawaccel not activating in valorant

### ISSUE THREAD

**Issue by MiamiSchools** [a1xd/rawaccel#156]
Whenever I open rawaccel and run it/run it as admin, it never feels like anything changed in-game. How do I fix this issue? I've tried re-adjusting the settings to others peoples and I still don't feel a difference at ALL.

**Comment by a1xd** [comment]
set sens multiplier to 10

if it still feels the same, then make sure any "disable" options in the Advanced -> Devices menu are unchecked
