### ISSUE TITLE
idk how to fix that

### ISSUE THREAD

**Issue by Ura1aa** [a1xd/rawaccel#160]
)
![Screenshot_1](https://user-images.githubusercontent.com/114833165/193428794-e4f88ae8-b9fa-4825-8e19-5e6c20c7e9ab.png)

**Comment by Moribax** [comment]
I have the same **problem**

**Comment by torriz** [comment]
You are missing required .NET Framework runtime. Follow the [guide](https://github.com/a1xd/rawaccel/blob/f88c562567612577ce149588056412248364f572/doc/Guide.md)

Use the official Discord server at [https://discord.gg/7pQh8zH](https://discord.gg/7pQh8zH) for support, not the Github issues tracker.

Note: The last version working on Windows 7 is [Rawaccel v1.5.1](https://github.com/a1xd/rawaccel/releases/tag/v1.5.1)
