### ISSUE TITLE
CAN SOMEOME HELP ME

### ISSUE THREAD

**Issue by Gardeee** [a1xd/rawaccel#161]
Bro i accidentaly turn my sens multiplier até 234 and i cant move my mouse to turn off.I NEED HELP NOW MAN PLS

**Comment by V0RY3X** [comment]
help

got the same problem

**Comment by V0RY3X** [comment]
but mine is 999999

**Comment by ThuyenBrian** [comment]
To fix go into safe mode and delete raw accel

**Comment by JacobPalecki** [comment]
Windows can be navigated with keyboard only. You can use windows search with windows key, tab, arrow keys, and enter to find and start rawaccel.exe and tab to the sens multiplier field, then to apply.
