### ISSUE TITLE
Add Hot-keys

### ISSUE THREAD

**Issue by elfasiShir** [a1xd/rawaccel#162]
Primarily to turn off.
If needed I can be assigned.

**Comment by a1xd** [comment]
i suggest using `writer.exe` with different configs (based on `settings.json`) for changing settings

the UI in its current state is not designed to be constantly running in the background, so hotkeys don't make much sense at the moment

**Comment by eugenesvk** [comment]
just a tip: you can use AutoHotkey for this to run writer with custom configs (and use more advanced starting triggers than whatever is usually available in any regular app like double tap right shift to turn on and double tap left shift to turn off)

```ahk
F3::Run('"path/to/rawaccel/writer.exe" "path/to/settings.json"')
F4::Run('"path/to/rawaccel/writer.exe" "path/to/settings_off.json"')
```
