### ISSUE TITLE
install issue 

### ISSUE THREAD

**Issue by nanunamzzy** [a1xd/rawaccel#164]
I
![image](https://user-images.githubusercontent.com/103026989/203798087-eb081a71-f93a-4a19-a865-d5409f7d54ce.png)
 just reinstalled windows 10 pro and i installed .net and directx and everything but im getting this error everytime i open installer.exe
 someone tell me how to fix this i've tried everything.

**Comment by a1xd** [comment]
you're missing the MSVC redist: https://aka.ms/vs/16/release/vc_redist.x64.exe
