### ISSUE TITLE
I have released a fix to apply rawaccel at boot. I am unsure where to contact appropriately. 

### ISSUE THREAD

**Issue by samfisherirl** [a1xd/rawaccel#168]
https://github.com/samfisherirl/RawAccel-Apply-at-Boot

simple program.

**Comment by serossi** [comment]
jeesus, tghats an autohotkey macro to start rawaccel.

way cleaner would be simply to load it via autorun at startup. that would also allow to run it befoire login which is nessesary for people scaling down very high dpi

**Comment by torriz** [comment]
It even has instructions to 

> create basic scheduled task to schedule "when i on login" and point to rawaccelboot.exe

while all you had to do was schedule the `writer.exe settings.json`  that comes with rawaccel :|

**Comment by samfisherirl** [comment]
> jeesus, tghats an autohotkey macro to start rawaccel.
> 
> way cleaner would be simply to load it via autorun at startup. that would also allow to run it befoire login which is nessesary for people scaling down very high dpi

from my experience, it requires clicking apply to work. not autorun

**Comment by Fuwn** [comment]
> It even has instructions to

Seeing how there's such a high frequency of issues related to autoruns, perhaps there should be a video or GIF of a complete example within the main README for adding Raw Accel to Windows' `shell:startup`.

This would likely solve more future issues than the effort to produce the PR.

**Comment by a1xd** [comment]
sorry, but using AHK is a hard no

and I agree Fuwn, updating the docs makes the most sense for now
