### ISSUE TITLE
This will make Raw Accel 100% better.

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [a1xd/rawaccel#170]
Hello there,
so not everyone is a low level programmer and in fact using low level to make a UI isn't very smart.
Because people who know UI very good don't use low level programming.
I would rather make the driver in C/C++ and use a higher level for UI so more people can contribute.
UI is just to configure the driver and even if it eats up much more than needed (like electron apps) it doesn't matter as the tiny high performance driver written in C/C++ will be running all time.

There are many UI things missing, just for example the way of making the "curves" is just bad, I would rather have some UI where I can use some Bezier Curves and then move some points and have it how I want it. Set min and max value of my sens.

I would much prefer this UI
https://mouseacceleration.com/home.html

How I use accel is by lowering my sens, so my flicking is on 1.0 and it works amazing, but then I use like 0.85-0.9 for tracking.
Sadly as soon as I set a limit of 1.0 the curves don't work... so the only thing I use is the rotation.

Look at FanControl on github :) Very easy to use, nice UI and runs really good, a magnitude better than any Mouse driver.

**Comment by JacobPalecki** [comment]
The UI for Raw Accel is written in C# using windows forms, not c, c++, or any other "low level programming" (by which I'm guessing you mean not memory-managed): https://github.com/a1xd/rawaccel/blob/master/grapher/Form1.cs

If you want to start a curve at x and go to 1, set a cap or limit of 1/x and a sensitivity multiplier of x.

You, or anyone, is free to create proposed changes which add desired features. We've had a few folks do that already. The writer.dll is C# and contains the function call needed to pass values to the driver, so it can be used to write an entire new UI should you or anyone be inclined to do so.

**Comment by 4e576rt8uh9ij9okp** [comment]
How does the "values" look like? Is it JSON or what is it exactly?
