### ISSUE TITLE
Raw accel high power usage issue

### ISSUE THREAD

**Issue by ywbycutie** [a1xd/rawaccel#172]
Whenever the "show velocity and gain" option is checked task manager detects raw accel using high amounts of power. On my system it goes up to moderate and rarely high but on my friend's system it goes to high and results in him stuttering ingame.

**Comment by Fuwn** [comment]
The reason for high resource usage during cases like this is explained in a comment [here](https://github.com/a1xd/rawaccel/issues/54#issuecomment-753555021).

If you aren't streaming or actively testing your curve, it's best to just close the GUI after you're finished applying.
