### ISSUE TITLE
I'm curious. Will rawaccel increase mouse latency?

### ISSUE THREAD

**Issue by Try2079** [a1xd/rawaccel#173]
I mainly use the Rotation function to play electronic sports games. I am curious whether rawaccel will cause delays. Thank you!

**Comment by IDIVASM** [comment]
i dont think so , it will decrease latencty because using aditional mouse cmd will add more delay but yea u can fix this buy using  xmousecontrol  here u can make the mouse click and release speed to 1ms 
wait i will attach the software btw do u play valo ? 
https://x-mouse-button-control.en.softonic.com/

**Comment by Try2079** [comment]
> i dont think so , it will decrease latencty because using aditional mouse cmd will add more delay but yea u can fix this buy using  xmousecontrol  here u can make the mouse click and release speed to 1ms 
> wait i will attach the software btw do u play valo ? 
> https://x-mouse-button-control.en.softonic.com/
> 

Thank you! I'm playing r6s, apex and csgo now. I'm terrible at valorant.😭

**Comment by Try2079** [comment]
So the delay it brings is about the same as the delay of the razer driver?

**Comment by IDIVASM** [comment]
> 

only way to fix  by playing it in 1000hz but i have doubt whether it will decrease latency or not

**Comment by KaJe5380** [comment]
> So the delay it brings is about the same as the delay of the razer driver?

Pretty sure the Razer driver only communicates to change sensor parameters. I don't think it processes any of the mouse movement. You are also stacking drivers on top of each other. So you would be stacking raw accel and razer drivers on top of each other. Still not noticable latency by the human eye.

If you are worried about latency, I'd be more worried about network latency, computer latency, and monitor latency.
8k polling rate mouse and etc.

I have 0 idea what IDIVASM is talking about though.

**Comment by Try2079** [comment]
> > So the delay it brings is about the same as the delay of the razer driver?
> 
> Pretty sure the Razer driver only communicates to change sensor parameters. I don't think it processes any of the mouse movement. I believe it's windows handling the actual mouse movement. You are also stacking drivers on top of each other. So you would be stacking raw accel and razer drivers on top of each other. Still not noticable latency by the human eye.
> 
> If you are worried about latency, I'd be more worried about network latency, computer latency, and monitor latency.
> 8k polling rate mouse and etc.
> 
> I have 0 idea what IDIVASM is talking about though.

Thank you for your serious answer. I was planning to uninstall the Razer driver before.🤣
