### ISSUE TITLE
unable to delte the rawaccel.sys

### ISSUE THREAD

**Issue by PokemonVashisth** [a1xd/rawaccel#174]
I recently installed raw accel but wanted to go back so I uninstalled. However, now my mouse is stuttering. And when I checked the drivers folder in system 32 the rawaccel.sys still exists and I think that's what's causing the sturreing.

Can anyone help?

**Comment by KaJe5380** [comment]
I'd guess the driver was still running and couldn't remove it. Try rebooting and then re-uninstalling the driver with uninstaller.exe as administrator. Reboot again after that. See if there is mouse stuttering after that?

I remember using InterAccel and having issues with uninstalling and needed to reboot first before uninstalling. The uninstalling then rebooting again after.

**Comment by a1xd** [comment]
also make sure you're rebooting through the start menu -> Power -> Restart option
