### ISSUE TITLE
Some suggested features. 

### ISSUE THREAD

**Issue by JonatannossreP** [a1xd/rawaccel#181]
It would be nice to be able to change between any number of different sensitivities and acceleration profiles with the press of any number of different global hotkeys or key combinations. Basic profiles in themselves would be nice, and even nicer if application sensitive. Different profiles for different mice would also be neat! 

Support for different speeds on the same axis which can be bound to keys like WASD. E.g. holding W = 100% - right and 100% left sensitivity. Holding A = 75% right sensitivity and 125% left sensitivity. 

At least a "sniper" button support so you can change your sensitivity when you press a button would be nice.

**Comment by a1xd** [comment]
will add basic profile support at some point, but keybinds are outside the scope of the project 

[see this for workarounds](https://docs.google.com/document/d/1GXWXl2nO_ee-Vp4Bw_eeGbHFQn4juT2Z_qfIWAcY7Aw/edit)
