### ISSUE TITLE
doesnt work when i open valorant

### ISSUE THREAD

**Issue by vandikadari** [a1xd/rawaccel#182]
it works fine until i open valorant then it stops working and when i close valorantit starts working again and kind of decreases my sens even if i insert the dpi and mouse hz correcty

**Comment by Geromo94** [comment]
Yes, my Valorant also resets the mouse settings, but I just press "apply" again directly in the game..

**Comment by a1xd** [comment]
it work for valerant

**Comment by dylan-chong** [comment]
Possibly related https://github.com/a1xd/rawaccel/issues/196
