### ISSUE TITLE
Any easy way to work with the driver, decoupled from UI?

### ISSUE THREAD

**Issue by dougg0k** [a1xd/rawaccel#183]
I didnt read the code, but is there a easy way to work with the driver lets say by using a API or specific exe with param/flags and pass the values from what you see in the UI and get the json?

Like a installer, uninstaller and writer.

This would open a way for someone to build a UI with more features, if whoever would not want to contribute to a C# codebase. 

I was thinking of this, as I am learning Rust, I thought to do something like this, but not sure I will have time. Would be good to know anyhow.

**Comment by a1xd** [comment]
you can work with the driver through wrapper lib, but it's dependent on .NET/CLR
