### ISSUE TITLE
automatic( after i applied settings to classic)  it selects to linear from classic 

### ISSUE THREAD

**Issue by rexy1288** [a1xd/rawaccel#186]
whenever I click apply on classic then automatic  my setting applied to linear .. I tried everything .. uninstalling , installing still nothing happened

**Comment by rexy1288** [comment]
I found same solved issue in previous question
suppose if I closed my raw accel after opening then its effect still on the mouse or i must have to keep open raw accel to use mouse acceleration

**Comment by a1xd** [comment]
yes, classic with power=2 changes to linear

and no you don't need to keep it open; you can just run it once when starting your PC, and close it
