### ISSUE TITLE
Mouse gets slower with higher DPI

### ISSUE THREAD

**Issue by yaboicrutches** [a1xd/rawaccel#188]
I tried googling everywhere for the answer to this before coming here. I'm pretty sure I know the answer but I just want to double check.

When I set the DPI from 1600 to 3200 the mouse gets slower. Everywhere I read people say that it gets faster the higher you go. Is this a problem with the mouse or my computer?

**Comment by learn2readme** [comment]
This is not a support forum. Go to discord for help

**Comment by a1xd** [comment]
don't bother with the DPI option in the UI, it's not changing the DPI of your mouse
