### ISSUE TITLE
Mouse Polling Rate

### ISSUE THREAD

**Issue by punxen** [a1xd/rawaccel#189]
Hello,
Could you please write a alternative driver in which the mouse polling rate is locked to 1000Hz even with slow mouse movements. I remember back in 2006, in Win XP my Logitech G5 always had a 1000Hz polling rate even with slow mouse movements.
Tested with “Mouse Rate Checker”. This meant that the aiming was always the same and very precise.

There are more and more people complaining about a inconsistent and floaty mouse.

You could be the first to solve this problem.

**Comment by a1xd** [comment]
i'm not familiar enough with usb drivers to do this
