### ISSUE TITLE
Suggestion: add an option to fix double-clicking (ignore rapid mouse clicks)

### ISSUE THREAD

**Issue by douglasb78** [a1xd/rawaccel#194]
Most mouses nowadays have lower "debounce times" to have a quicker response, but as time goes on and button switches wear out these lower times lead to double-clicking. Some manufacturers do allow users to adjust the debounce time within their software (such as Glorious, Roccat, GWolves) to achive faster responses or fix double-clicking, but not all. Adding such an option would help users mitage double-clicking without resorting to [AHK](https://web.archive.org/web/20180717202915/http://jslover.net/AutoHotkey/Scripts/Buggy-Mouse.ahk) and [X-Mouse](https://www.howisolve.com/how-to-fix-a-double-clicking-mouse-easily/), which conflict with anti-cheat systems.

(_An 'Ignore rapid clicks' option would allow users to specify a time in milliseconds to ignore clicks done too fast, held for just milliseconds.._)

I don't have double-clicking in my mouse, but I came across a Reddit post about it and immediately thought of rawaccel.

I believe it fits within this program.

[With the recent release of CS2 and the introduction of 'subtick' systems, the input has become almost instantaneous and is no longer 'locked' to the tickrate. Many users who didn't experience double-clicking issues in CS:GO are now encountering this problem in CS2. Even the tiniest millisecond of double-clicking is resulting in unintended double shots](https://www.reddit.com/r/cs2/comments/17chdgi/cant_consistently_single_tap_random_double_shots/)

**Comment by a1xd** [comment]
This could technically be added to RA, but it's out of scope, and I think it should be a standalone driver. I may find some time to write it myself, but ideally someone else would do it. If you can, let me know here or on discord; simon9435. I'll be able to take care of driver signing until Feb 2025.
