### ISSUE TITLE
DPI, Sens Multiplier

### ISSUE THREAD

**Issue by m1nuzz** [a1xd/rawaccel#195]
For example, I want to make from 800dpi to 25600dpi and in rawaccel I write "**_Sens multiplier_**" value **0.03125** but shows that "_**Current**_ **0.0312**" it is really **0.0312** or is it a bug? Or still can not be more than 4 characters after the dot?
![image](https://github.com/a1xd/rawaccel/assets/109736024/3101ec90-a24f-40e6-8881-8396c304fd6c)

**Comment by Sai-Moen** [comment]
The grapher doesn't show all of the decimals, but the numbers themselves are double-precision floating point, so you can have plenty of decimals before the precision runs out.
