### ISSUE TITLE
Suggestion: minimize to system tray

### ISSUE THREAD

**Issue by ivdccxi** [a1xd/rawaccel#200]
i love this application and i like having it on at all times i just wish i could minimize it to system tray so it wouldn't clutter my taskbar

**Comment by torriz** [comment]
You don't need to run the GUI if you're not actively working with it. Close it.

See [FAQ.md#does-the-gui-need-to-be-running-for-raw-accel-to-work](https://github.com/a1xd/rawaccel/blob/master/doc/FAQ.md#does-the-gui-need-to-be-running-for-raw-accel-to-work)
and 
[FAQ.md#does-the-gui-need-to-be-run-every-time-i-start-my-pc](https://github.com/a1xd/rawaccel/blob/master/doc/FAQ.md#does-the-gui-need-to-be-run-every-time-i-start-my-pc)

**Comment by lucas-teks** [comment]
Yes, it is frustrating to have the GUI popping on and having to close it on startup. With InterAccel we could add a "-m" argument, but this doesn't work on RawAccel. So the solution is to run the driver alone:

1. In the RawAccel folder you "Create a shortcut" for "writer.exe" & copy the fullpath of "settings.json" in this same folder.
2. `Window` + `R` > "shell:startup" > paste the "writer.exe" > go to its Properties > modify the target by pasting the fullpath of "settings.json" at the end separated by a space.

This will now run in silence on startup without the GUI, without tray system.

**Comment by hoakerk** [comment]
> Yes, it is frustrating to have the GUI popping on and having to close it on startup. With InterAccel we could add a "-m" argument, but this doesn't work on RawAccel. So the solution is to run the driver alone:
> 
> 1. In the RawAccel folder you "Create a shortcut" for "writer.exe" & copy the fullpath of "settings.json" in this same folder.
> 2. `Window` + `R` > "shell:startup" > paste the "writer.exe" > go to its Properties > modify the target by pasting the fullpath of "settings.json" at the end separated by a space.
> 
> This will now run in silence on startup without the GUI, without tray system.

Thanks Lucas!

**Note:** _In the RawAccel folder you "Create a shortcut" for "**writer.exe**"_.
And not of the main app as I did on autopilot :)
