### ISSUE TITLE
object VCRUNTIME140_1 . dll. not found try to install program again

### ISSUE THREAD

**Issue by Kooozli** [a1xd/rawaccel#203]
any solution for this?
![Screenshot 2024-03-07 151529](https://github.com/a1xd/rawaccel/assets/162595689/7c0f9079-4371-49e0-9782-9957d706e602)

**Comment by torriz** [comment]
yes, read the instructions.
https://github.com/a1xd/rawaccel/blob/master/doc/Guide.md
