### ISSUE TITLE
It won’t work

### ISSUE THREAD

**Issue by Tacotwelve** [a1xd/rawaccel#208]
I downloaded it right and it opens and works on the windows screen but then in any game it doesn’t work. Why is that.

**Comment by Crv5heR** [comment]
How much FPS do you have?

**Comment by hoakerk** [comment]
After configure accelerations, don't let UI run in background. It will consume CPU/GPU resources.
By the way, the settings will persist after closing UI, until next reboot. There is a way to auto apply settings without opening UI when you have all setup.
