### ISSUE TITLE
Question that's not answered in the FAQ or Guide

### ISSUE THREAD

**Issue by nitram3** [a1xd/rawaccel#217]
If it is answered I apologise but I couldn't find it. 

My question is do I have to turn off windows acceleration or does rawaccel replace it automatically. And if so, does "off" mean it's using the windows' default?

**Comment by KaJe5380** [comment]
Turn off Windows OS mouse accel just to be safe. 

Raw accel will basically be your new mouse input. Which means Windows will probably use it and then stack its own accel on top of your curve.

**Comment by nitram3** [comment]
So yeah, @KaJe5380 was correct. You do have to turn off Windows acceleration (enhance mouse precision) in case anyone else is wondering the same thing.
