### ISSUE TITLE
Sens Multiplier Effect

### ISSUE THREAD

**Issue by CristianoLira** [a1xd/rawaccel#225]
I have a Logitech G403 and I tested using a sensitivy multiplier of 0.25 with a 4xdpi (2400) and I found that aiming becomes much more precise/easy, independent of the dpi/sens I set, I tried increasing the sens to get the same edpi with a multiplier of 1 and tune the sens trying to find if it was just the dpi that made me feel that, but it's not the case, Raw Accel does something to the mouse input when setting the multiplier to 0.25 or something that makes aiming much more precise. What RawAccel is doing? PS: I don't use accel, only the multiplier option. I would like to know if I could replicate that without Raw Accel and why tracking/aiming becomes much better with this option and why my mouse isn't already precise in the first place. Tested on CS 2.

**Comment by JacobPalecki** [comment]
There is no change at all in actual output between increasing your DPI by a factor of 4 and setting sensitivity multiplier to 0.25, if Raw Accel's other features like acceleration or rotation are not being used. Do you have any physical measurements to indicate a change in output?

**Comment by CristianoLira** [comment]
Not physical, but the difference is clear to me, night and day, aiming becomes much easier and more precise, hitting easily hard shots than what I normally do. And I couldn't replicate that using a low in-game sens to match the same edpi (w/ a 1 multiplier) so I would like to understand what is happening and if I could replicate that without any software to not be dependent on Raw Accel.

**Comment by JacobPalecki** [comment]
There's no physical difference, so this is not a Raw Accel issue.
