### ISSUE TITLE
Re-add the pre-scaler or adapt the conversion program

### ISSUE THREAD

**Issue by systemofapwne** [a1xd/rawaccel#34]
I am struggeling to get my old settings transitioned to this new awesome driver.
It looks like, the conversion program and the explanaition will not fully work.

Here is my old settings.txt

```
Sensitivity = 0.85
Acceleration = 0.26
SensitivityCap = 4
Offset = 0
Power = 2
Pre-ScaleX = 0.033333
Pre-ScaleY = 0.033333
Post-ScaleX = 0.4
Post-ScaleY = 0.4
AngleAdjustment = 0
AngleSnapping = 0
SpeedCap = 0
FancyOutput = 0
```

What it does: Scales down my 12000 DPI of the mouse to 400, applies an acceleration curve (close to what Windows uses) and then scales it further down via post-scale.
It looks like, your simple formula "Acceleration/Sensitivity)*PreScale" does not apply. My mouse is way to fast at 12000 DPI right now.

**Comment by systemofapwne** [comment]
So what I figured now, the adjusted sensitivity via accelerion of the [original code](https://github.com/KovaaK/InterAccel/blob/master/99.%20source/accel.cpp) looks like this (pseudo-syntax)

```
rate = sqrt(dx^2 + dy ^2)
accSens = 1 + (preScaler * rate * acceleration)^Power/sensitivity
```

Your tutorial suggest to use (preScaler * acceleration/sensitivity) to get the new accel value. But this omits the Power completely around (preScaler * acceleration) part, which does not affect the sensitivity though. Maybe someone can dig deepter?

**Comment by systemofapwne** [comment]
I updated my previous post since I digged in deeper. With my rules applied at the end of the second post, my old 

settings.txt
```
Sensitivity = 0.85
Acceleration = 0.26
SensitivityCap = 4
Offset = 0
Power = 2
Pre-ScaleX = 0.033333
Pre-ScaleY = 0.033333
Post-ScaleX = 0.4
Post-ScaleY = 0.4
AngleAdjustment = 0
AngleSnapping = 0
SpeedCap = 0
FancyOutput = 0
```

transforms to this settings.json file
```
{
  "GUISettings": {
    "DPI": 1200,
    "PollRate": 1000,
    "ShowLastMouseMove": true,
    "ShowVelocityAndGain": false
  },
  "Driver settings": {
    "### Mode Types ###": "linear | classic | natural | naturalgain | power | motivity | noaccel",
    "Degrees of rotation": 0.0,
    "Use x as whole/combined accel": true,
    "Accel modes": {
      "x": "linear",
      "y": "noaccel"
    },
    "Accel parameters": {
      "x": {
        "offset": 0.0,
        "legacyOffset": true,
        "acceleration": 0.010195976470588236,
        "scale": 1.0,
        "limit": 2.0,
        "exponent": 2.0,
        "midpoint": 10.0,
        "weight": 1.0,
        "legacyCap": 4.7,
        "gainCap": 0.0
      },
      "y": {
        "offset": 0.0,
        "legacyOffset": true,
        "acceleration": 0.0,
        "scale": 1.0,
        "limit": 2.0,
        "exponent": 2.0,
        "midpoint": 10.0,
        "weight": 1.0,
        "legacyCap": 0.0,
        "gainCap": 0.0
      }
    },
    "Sensitivity multipliers": {
      "x": 0.0133332,
      "y": 0.0133332
    }
  }
}
```

This now completely replicates my old curve.
In essense, the convert tool is bugged.
And you can not convert all curves (especially the nonlinear curves) from InterAccel to RawAccel, when a prescaler had been used in InterAccel, since a prescaler is missing in RawAccel by design.

**Comment by a1xd** [comment]
Ah I see, so post-scale and cap are not converted correctly in your case.
I'll add your conversions for those, and try to fix non-linear conversion too.
Thanks!

**Comment by JacobPalecki** [comment]
This is my fault - wrote quickly for linear case. Will fix.
