### ISSUE TITLE
windows 7

### ISSUE THREAD

**Issue by eglacias** [a1xd/rawaccel#39]
windows 7 support? cant be that complicated can it, for a mouse driver? windows 10 is faaaaaar to dismal for office use, and ive been waiting for something with inertia as interaccel is static, not a smooth mouse feel....

**Comment by a1xd** [comment]
i just got around to making a Win7-compatible build, and now i just want more feedback before releasing it. 

so far only one person has used it on Win7, they said it worked fine after updating .NET.

uploaded here if you want to try it out:
https://github.com/a1xd/rawaccel/releases/tag/v1.2.0-w7

building the driver for Win7 is easy enough, but the driver signing process is becoming much more complicated in early 2021, so Win7/Win8 support will be dropped at that point.

**Comment by Dwarden** [comment]
q, what version of .net is the minimal requirement for it to work properly ?

**Comment by a1xd** [comment]
yea .NET Framework 4.7.2+ works.

and no, after you set your config with either rawaccel.exe or `writer.exe path/to/settings.json`, it stays active until you reboot

**Comment by Dwarden** [comment]
well i tried it and it seems the settings activate only when `rawaccel.exe` is running (W7SP1x64 EOS)

**Comment by a1xd** [comment]
i'd guess it just feels that way because your accel settings are subtle

try something extreme, for example set sens multiplier to 0.01 > hit apply > close gui
