### ISSUE TITLE
add and expose driver/gui version

### ISSUE THREAD

**Issue by waldfee** [a1xd/rawaccel#40]
currently the driver does not have it's version fields filled out.
this makes it impossible to determine if the current install is out of date.

**i think the following would be really helpful**

- add version information to the driver
- add version information to the gui (currently the exe has set 1.0.0.0 regardless of version)
- display both version numbers in the gui (maybe under "about" menu, pretty much standard practice)
- the displayed driver version should be the one installed in the system, not the one of the `rawaccel.sys` file in the rawaccel folder

![image](https://user-images.githubusercontent.com/8242778/97687468-e1782d00-1a99-11eb-9020-42c9773b3937.png)
(information displayed by [nirsoft's utility](https://www.nirsoft.net/utils/installed_drivers_list.html))

**Comment by a1xd** [comment]
agreed, i'll get to this soon, and add better version mismatch handling to the gui.
