### ISSUE TITLE
Not applying on startup

### ISSUE THREAD

**Issue by GHz3r0** [a1xd/rawaccel#43]
Despite having the option checked, the curve is only applied after launching the GUI.

**Comment by facboy** [comment]
I suspect it means 'apply on startup of the GUI', which is perhaps not what ppl would usually expect.

**Comment by Irevall** [comment]
Try this: https://www.reddit.com/r/MouseAccel/comments/jow79w/make_rawaccel_startup/gbbtdpk/

**Comment by JacobPalecki** [comment]
The above two comments pretty much handle this.
