### ISSUE TITLE
Permanently messed up my microphone driver

### ISSUE THREAD

**Issue by bixxly** [a1xd/rawaccel#44]
Started using this out of a recommendation, was really good and improved my aim a lot. Go to talk to my teammates and they complain about my mic, never had something like this happen before. I go to check Audacity and see it clipping a lot! Maxed out volume! I turn the microphone level all the way down and you can hear a static sound develop. I decide to uninstall the driver and restart my computer; still there! I'm looking for a new driver right now, I love this system and it really helped my aim but I want to not have a bad microphone at the same time.

**Comment by a1xd** [comment]
So you're still having mic issues after uninstalling the driver? It must be unrelated.
