### ISSUE TITLE
not starting at 0.25

### ISSUE THREAD

**Issue by blank911** [a1xd/rawaccel#47]
hi, i'm loving rawaccel, i was just wondering, i'm used to 400 dpi so i do 1600 with 0.25, acc on 0.04 and cap at 4. The output starts at 0.25 but the red dot never actually is on 0.25 is that just visual? What do i have to do to fix it if not. It works fine with acc on 0.025 but thats to slow for me.

**Comment by a1xd** [comment]
it's visual, the red dot just shows an approximation of your speed/input.
