### ISSUE TITLE
Can Decrease mouse speed Acceleration/speed on Y axis ?

### ISSUE THREAD

**Issue by MarvenX97** [a1xd/rawaccel#50]
hello,

i'm trying to decrease my  mouse speed Acceleration/speed on Y axis one the mouse reaches a desired poinet like this photo! 
!

[accel](https://user-images.githubusercontent.com/37535970/102724113-74e91400-430d-11eb-9f27-e82dcf210eba.png)

**Comment by a1xd** [comment]
from the advanced menu set
- cap style > legacy
- application style > by component

then you can use classic mode for the y component with
- sens cap in (0, 1]
- negative weight
- exponent >2

![Capture](https://user-images.githubusercontent.com/68629610/102836774-42502180-43c8-11eb-8515-ee3d2b70ab35.JPG)

**Comment by MarvenX97** [comment]
Exactly what i'm looking for :) thanks mate
