### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by iamchairs** [a1xd/rawaccel#54]
Running on an i7-8750H. Having 17-18% of my CPU being used by Raw Accel during use is alarming.

![Screenshot 2021-01-02 183055](https://user-images.githubusercontent.com/4390732/103469319-cf7c6a00-4d28-11eb-8181-790f59b7209d.png)

What is Raw Accel doing to justify this much CPU usage?

**Comment by JacobPalecki** [comment]
You can close rawaccel.exe and acceleration is still applied. The actual acceleration is performed in the driver which runs in kernel space, and rawaccel.exe runs in user space with the purpose of handing new settings to the driver and displaying graphs of those settings to the user.
The reason rawaccel.exe uses such high cpu is that it refreshes the graphs 100 times per second to show the last mouse move. There is unfortunately not a more reasonable to achieve low latency and high FPS for the mouse move without a lot of work or a different GUI framework. So, use rawaccel.exe to determine and set the settings you like and then you can close it, and acceleration will still be applied by the driver.

**Comment by iamchairs** [comment]
Ah ok then. Well that's not a problem if it continues to run when closed. Thank you.
