### ISSUE TITLE
Is there a way of applying the accel at startup? 

### ISSUE THREAD

**Issue by HitGub-Shiro** [a1xd/rawaccel#55]
My current way is a batch file that starts and closes rawaccel.exe in the startup folder, yeah its not an ideal way i guess but I found no autostart or that kind, it would also be okay if it runs in the background like most programs, if its not updating 100 times the second. But like that, idk.

**Comment by a1xd** [comment]
you can pass your config to writer: `writer.exe settings.json`

**Comment by power9maker** [comment]
> you can pass your config to writer: `writer.exe settings.json`

Is this really necessary for it to work on startup?
For me it used to startup with windows, but since 2 days ago I have to open it manually/automate it with a batch file.

**Comment by a1xd** [comment]
yeah it's always been necessary
> it used to startup with windows

an explanation for this could be windows 10 "fast startup" option, which saves kernel state on shutdown
