### ISSUE TITLE
How do I raise my Y axis acceleration without touching my X axis at all? (keeping my X axis 1:1)

### ISSUE THREAD

**Issue by KingOwnageXV** [a1xd/rawaccel#61]

**Comment by GitLinker** [comment]
In Raw Accel, there should be (on the top left of the window)
Advanced Settings > Application Style > By Component
X = Y (uncheck Lock X & Y)
Then set your Y axis acceleration, and your x axis should stay 1:1

https://github.com/a1xd/rawaccel/blob/master/doc/FAQ.md
> Separate x and y prescale values, which no one should have, are not supported in Raw Accel. For something similar but better, check out the "By Component" section of the guide.

or look into issue #50 as they both talked about the separation by component

**Comment by JacobPalecki** [comment]
There is a more in-depth answer here. By Component does technically answer the question but it also has some behavior, called curl, which might not be desirable to some users. If you have By Component enabled and you move your mouse diagonally, while increasing its speed, the cursor won't move in a straight line but will slightly curl. I am introducing some options for Whole mode which will allow users to control the range and domain of x motions vs y motions in a continuous and curl-less way in the next release.
