### ISSUE TITLE
Easier to read error messages?

### ISSUE THREAD

**Issue by GitLinker** [a1xd/rawaccel#62]
![image](https://user-images.githubusercontent.com/23021795/104500495-5df7b380-5593-11eb-9e4c-198ec8b279fb.png)

Potentially making an easier error message with your own message box, as most users will not understand nor need the unhandled exception part. No good reason to clamp it to a valid number, as then users may continually try putting a negative offset. Just a suggestion for a future update and not application breaking😄

**Comment by a1xd** [comment]
yeah abusing the exception dialog is not really appropriate here, i'll fix this in the next release
