### ISSUE TITLE
Automatically adjust position of Anisotropy by component type when using "Classic"

### ISSUE THREAD

**Issue by GitLinker** [a1xd/rawaccel#68]
![image](https://user-images.githubusercontent.com/23021795/105458645-d28abc00-5c3d-11eb-9731-83707ed938f8.png)
You can see that the Anisotropy runs into some acceleration curve options when selected.
This is quite an issue but I'd assume not a hard one to fix.

**Comment by JacobPalecki** [comment]
![image](https://user-images.githubusercontent.com/16246195/105464837-01f1f680-5c47-11eb-9b8a-ade45ac5c055.png)

**Comment by JacobPalecki** [comment]
Interesting. It does not happen for me. I'll investigate.

**Comment by GitLinker** [comment]
> 
> 
> Interesting. It does not happen for me. I'll investigate.

I found out the issue, but it's still needs to be fixed
When using "By Component", the "X=Y" will appear, which adds to the y offset of all the controls
But, you are using "Whole"

**Comment by a1xd** [comment]
fixed by #69
