### ISSUE TITLE
Support for applying acceleration to more than one mouse, but less than all of them

### ISSUE THREAD

**Issue by bakester14** [a1xd/rawaccel#76]
I am loving RawAccel, thank you!

One thing that would make it slightly more optimized for my use case is the ability to apply the acceleration profile to any number of mice, rather than just one mouse or all mice. Windows 10 recognizes 3 mice on my PC - a trackball that I use for work, a wireless gaming mouse, and that same mouse when it's plugged in. I want the acceleration profile to apply to the "two" gaming mice, but not to the trackball, which is impossible through the current settings.

I'll poke around in source myself and see if this is easy enough for someone like me to get to, but wanted to raise a formal issue. Thanks again for the great driver!

**Comment by a1xd** [comment]
how about adding a flag which turns the device "whitelist" into a blacklist?

implementing per-device settings is definitely possible, but more complicated. i am trying to avoid it to be honest

**Comment by bakester14** [comment]
Whitelist/Blacklist would work! I will try taking a look at this tonight.

**Comment by GrayFace** [comment]
That's not enough. What would be great is a way to apply different configs to different mice. Or to just correct for DPI difference.

**Comment by a1xd** [comment]
finally got around to properly implementing this in v1.6
in the new Device menu you can individually set devices as disabled

@GrayFace you can also set dpi from this menu, and note that the polling rate field here just disables the standard behavior; where polling is adjusted for automatically

also i'm planning to add support for #74/linking devices to different configs in 1.7
