### ISSUE TITLE
when i downloaded this my 144hz monitor was capped at 60hz 

### ISSUE THREAD

**Issue by idkwhatnametohave1** [a1xd/rawaccel#78]
idk why this happened pls help

**Comment by a1xd** [comment]
you mean it was set to 60hz after running the installer and rebooting right? 

weird, i'd guess there was some unrelated pending reboot operation/driver update that caused it

if you search 'advanced display info' from the taskbar/start menu on win 10, can you set it back to 144hz from there?

**Comment by idkwhatnametohave1** [comment]
i've tried to set it back but it says that its at 144hz but its very obvious its not ive tryed reinstalling but whenever its installed my monitor is at 60hz so im not sure what to do

**Comment by a1xd** [comment]
try updating your graphics driver? just throwing out ideas, i've never seen this issue before
