### ISSUE TITLE
Mouse randomly jerking while acceleration enabled

### ISSUE THREAD

**Issue by LudusLight** [a1xd/rawaccel#82]
Hi - When Raw Accel is enabled, every few seconds my mouse jerks in a random direction while moving it. If there's any more info I can provide please let me know.

Video of this happening (the 4 second mark) - https://www.youtube.com/watch?v=utiBwGwX0xE

My settings - 
![image](https://user-images.githubusercontent.com/7528518/111076790-d3accc80-84bb-11eb-9b4c-66f51ca1b1b4.png)

Thanks.

**Comment by a1xd** [comment]
if the direction is changing randomly, then this must be a sensor related issue

however from that clip it looks like the direction stayed roughly the same, and there was a change in speed that caused the crosshair to jump. i think a combination of unstable polling + your high acceleration might be producing this effect

are you using a wireless mouse? if so, test out a wired one, they are generally more stable

**Comment by LudusLight** [comment]
I am using a wireless mouse, however this problem is only evident when using Raw Accel. Disabling it leads to the issue not being present.

I will go ahead and test a wired mouse and report if the problem is still there.

**Comment by JacobPalecki** [comment]
See https://github.com/a1xd/rawaccel/issues/79
