### ISSUE TITLE
Profile isn't applied at startup

### ISSUE THREAD

**Issue by arsum04** [a1xd/rawaccel#83]
There are sometimes when I start my computer and my rawaccel settings aren't applied. I have to open the app and hit apply to get it to work again. Anyone else have this issue?

**Comment by GitLinker** [comment]
Slow driver initialization on startup #75
Not applying on startup #43
Is there a way of applying the accel at startup? #55
These have all been closed though and solved.

**Comment by arsum04** [comment]
thanks, that solves it 👍
