### ISSUE TITLE
Mouse freezing up for one second, repeatedly

### ISSUE THREAD

**Issue by wwboynton** [a1xd/rawaccel#84]
So I know that the driver is built to freeze up for 1000ms on changes. The thing is, some amount of time after launching the program...it starts doing it about every ten seconds. It might be a day before it happens, it might be ten minutes, but without fail, it starts doing it over and over. I've tried:

- Disabling running it on startup and doing it manually
- Turning it off entirely and using no accel for several days to see if it's an unrelated problem
- Hitting "Apply" to reapply settings

No dice. Anyone else had this issue or a fix for it?

**Comment by a1xd** [comment]
on startup, are you running the GUI program or `writer.exe`? 
if you use the GUI, does this still happen after closing it? your settings and the driver would still be active

a 1 sec cursor freeze is unheard of to me. it shouldn't freeze when changing settings either, there's just a delay on the new profile taking effect; your mouse should always be responsive

**Comment by JacobPalecki** [comment]
Closing - there really isn't anything in Raw Accel that could be causing this, as far as we are aware, and @a1xd pointed out some possible causes.
