### ISSUE TITLE
Feature: Minimize on start

### ISSUE THREAD

**Issue by AtHeartEngineer** [a1xd/rawaccel#91]
Can we get an option to have it minimize on start? I set it up to auto start with windows, and it would be really awesome if it minimized on start, or better yet, minimized to the system tray on start. Thanks, love raw accel.

**Comment by JacobPalecki** [comment]
Hello,
Per the FAQ:

"Does the GUI need to be running for Raw Accel to work?
No. Once settings are passed to the driver by the GUI, they stay in use until the computer is shut down."

Instead of minimizing the GUI, you should close it.
