### ISSUE TITLE
Which debugger do I use? (New to programming)

### ISSUE THREAD

**Issue by uhdcc** [a1xd/rawaccel#93]
I can't figure out which debugger to use. I tried them all and got errors. 

https://imgur.com/a/nFEDhdm

I was able to build successfully.

**Comment by a1xd** [comment]
kernel debugging is a bit of a pain to set up, and it's best to ignore the options in VS

you need to connect your PC to another, which is the "target", and where the driver is loaded. [this target can be a VM](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-network-debugging-of-a-virtual-machine-host)

here's a guide to get started if you want to go down this route: 
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode-
i haven't bothered with this much, and have gotten by using `DbgPrint()` and [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview)

either way, i suggest running debug builds in a VM. VMware workstation player works alright for me, and it supports USB passthrough
