### ISSUE TITLE
Interception + rawaccel Patched ?

### ISSUE THREAD

**Issue by freak101** [a1xd/rawaccel#94]
yesturday after a small valorant patch, when I inject Valolrant (which is based on interception drivers) & start valorant the 32 bit process which has been injected with valolrant crashes. I am pretty sure Interception + rawaccel has been patched.

**Comment by JacobPalecki** [comment]
You must have RawAccel confused with another program. RawAccel does not use the interception driver, does not require any "injection", and does not require any special 32-bit processes running alongside Valorant.
