### ISSUE TITLE
Autostart on Windows 11 not working

### ISSUE THREAD

**Issue by chrisheib** [a1xd/rawaccel#95]
Hey there, first of all thanks for the awesome app <3 

While running on Win10 I sometimes had the problem that rawaccel wouldn't function on startup. I needed to start the client, then after the grace period my mouse speed would ajust. This would happen rarely, but predictably around updates. 

After updating to Windows 11, rawaccel seems to never work on startup and I have to open the client every time. This is quite annoying ^^' (It might have worked one time, but maybe I just dreamed that up.)

I tried: 
- Upgrading to the latest version
- Uninstalling and reinstalling
- Toggling the autostart off and on

Any ideas what else to try? Or is this an incompatibility with Win11?

**Comment by torriz** [comment]
Are you using scheduled task to autostart it? 
If not, try that.
Task, after login, delay 5 sec

**Comment by JacobPalecki** [comment]
The "AutoWriteToDriverOnStartup" setting is poorly named, and does not cause your settings to be applied on windows startup. There are instructions in the pinned posts of our discord on some ways you can automatically run "writer.exe settings.json" on startup, which will have the desired effect.
