### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by iver0** [a1xd/rawaccel#96]
Is there any hope whatsoever for Linux version of RawAccel? Really the only thing holding me back from switching to Linux is lack of RawAccel or some other good mouse acceleration software, I just can't go back to no mouse accel at all, I play worse without it, and I'm a very competitive gamer.

**Comment by r4ttmann** [comment]
I'm interested in a Linux version too! I switched to linux a few weeks back. I have never used RawAccel before, but I heard good things about it and would like to give it a try.

**Comment by JacobPalecki** [comment]
The GUI is written in windows forms, and the guts of the driver (installation, the logic around receiving mouse counts and placing in queue, etc.) are completely unique to Windows. Only the acceleration algorithms could be used for a linux version. Seeing as this driver was written to be compatible with competitive game anti-cheat, and there are almost no such anti-cheats written for linux, we don't have a reason or desire to make a linux version. There are people on our discord who are knowledgeable about how you might implement your own mouse accel algorithms on linux.
